spring:
  application:
    name: eureka-server
server:
      port: 8090
      
eureka:
        instance:
          hostname: 192.168.203.109
client:
         registerWithEureka: false
         fetchRegistry: false
serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   server: 
    enable-self-preservation: false